// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type captureEventsDnsRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	CgroupId    uint64
	ArrivalNs   uint64
	Skaddr      uint64
	Len         uint32
	Family      uint16
	Direction   uint8
	Transport   uint8
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	Comm        [16]int8
	Payload     [1024]uint8
	_           [4]byte
}

type captureEventsGoTlsKey struct {
	_         structs.HostLayout
	Goroutine uint64
	Frame     uint64
	Pid       uint32
	Direction uint32
}

type captureEventsGoTlsPending struct {
	_           structs.HostLayout
	Connection  uint64
	Buffer      uint64
	Num         uint64
	StackOffset uint64
	Marked      uint8
	_           [7]byte
	Started     uint64
}

type captureEventsGoTlsWrites struct {
	_      structs.HostLayout
	Active uint64
	Closed uint64
}

type captureEventsHttpCursor struct {
	_         structs.HostLayout
	Pointer   uint64
	Left      uint64
	Remaining uint64
	Offset    uint64
	Segment   uint64
	Iov       uint64
	NrSegs    uint64
	Kind      uint64
}

type captureEventsHttpRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	CgroupId    uint64
	Skaddr      uint64
	Len         uint32
	Family      uint16
	Direction   uint8
	Kind        uint8
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	Comm        [16]int8
	Offset      uint32
	Payload     [16384]uint8
}

type captureEventsHttpRecvPending struct {
	_      structs.HostLayout
	Skaddr uint64
	Buffer uint64
	Limit  uint64
	Iov    uint64
	NrSegs uint64
}

type captureEventsHttpSendPending struct {
	_      structs.HostLayout
	Skaddr uint64
	Buffer uint64
	Limit  uint64
	Iov    uint64
	NrSegs uint64
}

type captureEventsHttpStreamKey struct {
	_         structs.HostLayout
	Skaddr    uint64
	Direction uint64
}

type captureEventsMysqlSendPending struct {
	_      structs.HostLayout
	Send   captureEventsHttpSendPending
	Server uint8
	_      [7]byte
}

type captureEventsNssCallKey struct {
	_      structs.HostLayout
	Thread uint64
	Stack  uint64
	Cookie uint64
}

type captureEventsNssControl struct {
	_    structs.HostLayout
	Fd   uint64
	Mode uint32
	Kind uint32
}

type captureEventsNssIoCall struct {
	_       structs.HostLayout
	Cookie  uint64
	Pending captureEventsSslPending
}

type captureEventsNssIoKey struct {
	_      structs.HostLayout
	Thread uint64
	Stack  uint64
}

type captureEventsSockOwner struct {
	_        structs.HostLayout
	CgroupId uint64
	Pid      uint32
	Comm     [16]int8
	_        [4]byte
}

type captureEventsSslKey struct {
	_    structs.HostLayout
	Tgid uint64
	Ssl  uint64
}

type captureEventsSslPending struct {
	_         structs.HostLayout
	Ssl       uint64
	Buffer    uint64
	Num       uint64
	Out       uint64
	Direction uint8
	Learned   uint8
	_         [6]byte
	Snapshot  captureEventsSslSnapshot
}

type captureEventsSslSnapshot struct {
	_           structs.HostLayout
	Skaddr      uint64
	Family      uint16
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	_           [2]byte
}

type captureEventsTcpDiagnostics struct {
	_          structs.HostLayout
	Valid      uint32
	RttUs      uint32
	RttvarUs   uint32
	Cwnd       uint32
	Ssthresh   uint32
	Unacked    uint32
	Lost       uint32
	ZeroWindow uint32
}

type captureEventsTlsPrefix struct {
	_        structs.HostLayout
	Bytes    [9]uint8
	Count    uint8
	Terminal uint8
	_        [1]byte
	Offset   uint32
	HelloEnd uint32
}

type captureEventsUdpSendPending struct {
	_           structs.HostLayout
	Skaddr      uint64
	Bytes       uint64
	Family      uint16
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	_           [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	captureEventsMapAnnouncedOwners            = "announced_owners"
	captureEventsMapDnsArrivals                = "dns_arrivals"
	captureEventsMapDnsQueryPending            = "dns_query_pending"
	captureEventsMapDnsScratch                 = "dns_scratch"
	captureEventsMapEvents                     = "events"
	captureEventsMapGoTlsPending               = "go_tls_pending"
	captureEventsMapGoTlsWrites                = "go_tls_writes"
	captureEventsMapHttpCursors                = "http_cursors"
	captureEventsMapHttpRecvPending            = "http_recv_pending"
	captureEventsMapHttpScratch                = "http_scratch"
	captureEventsMapHttpSendPending            = "http_send_pending"
	captureEventsMapHttpStreams                = "http_streams"
	captureEventsMapLostEvents                 = "lost_events"
	captureEventsMapLostLines                  = "lost_lines"
	captureEventsMapMysqlSendPending           = "mysql_send_pending"
	captureEventsMapNssConfigs                 = "nss_configs"
	captureEventsMapNssControlCalls            = "nss_control_calls"
	captureEventsMapNssDefaults                = "nss_defaults"
	captureEventsMapNssIoCalls                 = "nss_io_calls"
	captureEventsMapSockOwners                 = "sock_owners"
	captureEventsMapSslPending                 = "ssl_pending"
	captureEventsMapSslSocks                   = "ssl_socks"
	captureEventsMapTcpDiagnostics             = "tcp_diagnostics"
	captureEventsMapTcpEstablishedAt           = "tcp_established_at"
	captureEventsMapTcpLengthPending           = "tcp_length_pending"
	captureEventsMapTlsPrefixes                = "tls_prefixes"
	captureEventsMapTlsUnmapped                = "tls_unmapped"
	captureEventsMapUdpSendPending             = "udp_send_pending"
	captureEventsProgGoTlsArm64CloseEntry      = "go_tls_arm64_close_entry"
	captureEventsProgGoTlsArm64ReadEntry       = "go_tls_arm64_read_entry"
	captureEventsProgGoTlsArm64ReadExit        = "go_tls_arm64_read_exit"
	captureEventsProgGoTlsArm64WriteEntry      = "go_tls_arm64_write_entry"
	captureEventsProgGoTlsArm64WriteExit       = "go_tls_arm64_write_exit"
	captureEventsProgGoTlsCloseEntry           = "go_tls_close_entry"
	captureEventsProgGoTlsReadEntry            = "go_tls_read_entry"
	captureEventsProgGoTlsReadExit             = "go_tls_read_exit"
	captureEventsProgGoTlsWriteEntry           = "go_tls_write_entry"
	captureEventsProgGoTlsWriteExit            = "go_tls_write_exit"
	captureEventsProgHttpTcpDestroySock        = "http_tcp_destroy_sock"
	captureEventsProgInetCskAcceptEntry        = "inet_csk_accept_entry"
	captureEventsProgInetCskAcceptExit         = "inet_csk_accept_exit"
	captureEventsProgInetCskAcceptExitLegacy   = "inet_csk_accept_exit_legacy"
	captureEventsProgInetSockSetState          = "inet_sock_set_state"
	captureEventsProgInetStreamConnectEntry    = "inet_stream_connect_entry"
	captureEventsProgMbedReadEntry             = "mbed_read_entry"
	captureEventsProgMbedWriteEntry            = "mbed_write_entry"
	captureEventsProgNssAcceptEntry            = "nss_accept_entry"
	captureEventsProgNssCloseEntry             = "nss_close_entry"
	captureEventsProgNssControlExit            = "nss_control_exit"
	captureEventsProgNssDefaultEntry           = "nss_default_entry"
	captureEventsProgNssImportEntry            = "nss_import_entry"
	captureEventsProgNssIoExit                 = "nss_io_exit"
	captureEventsProgNssOptionEntry            = "nss_option_entry"
	captureEventsProgNssReadEntry              = "nss_read_entry"
	captureEventsProgNssRecvEntry              = "nss_recv_entry"
	captureEventsProgNssWriteEntry             = "nss_write_entry"
	captureEventsProgRustlsExit                = "rustls_exit"
	captureEventsProgSkbConsumeUdpEntry        = "skb_consume_udp_entry"
	captureEventsProgSslFreeEntry              = "ssl_free_entry"
	captureEventsProgSslReadEntry              = "ssl_read_entry"
	captureEventsProgSslReadExEntry            = "ssl_read_ex_entry"
	captureEventsProgSslReadExExit             = "ssl_read_ex_exit"
	captureEventsProgSslReadExit               = "ssl_read_exit"
	captureEventsProgSslWriteEntry             = "ssl_write_entry"
	captureEventsProgSslWriteExEntry           = "ssl_write_ex_entry"
	captureEventsProgSslWriteExExit            = "ssl_write_ex_exit"
	captureEventsProgSslWriteExit              = "ssl_write_exit"
	captureEventsProgTcpCleanupRbufEntry       = "tcp_cleanup_rbuf_entry"
	captureEventsProgTcpCreateOpenreqChildExit = "tcp_create_openreq_child_exit"
	captureEventsProgTcpDestroySock            = "tcp_destroy_sock"
	captureEventsProgTcpReceiveReset           = "tcp_receive_reset"
	captureEventsProgTcpRecvLength             = "tcp_recv_length"
	captureEventsProgTcpRecvmsgEntry           = "tcp_recvmsg_entry"
	captureEventsProgTcpRecvmsgExit            = "tcp_recvmsg_exit"
	captureEventsProgTcpRecvmsgExitLegacy      = "tcp_recvmsg_exit_legacy"
	captureEventsProgTcpRetransmitSkb          = "tcp_retransmit_skb"
	captureEventsProgTcpSendLength             = "tcp_send_length"
	captureEventsProgTcpSendReset              = "tcp_send_reset"
	captureEventsProgTcpSendmsgEntry           = "tcp_sendmsg_entry"
	captureEventsProgTcpSendmsgExit            = "tcp_sendmsg_exit"
	captureEventsProgUdpEnqueueEntry           = "udp_enqueue_entry"
	captureEventsProgUdpSendSkbEntry           = "udp_send_skb_entry"
	captureEventsProgUdpSendSkbExit            = "udp_send_skb_exit"
	captureEventsProgUdpV6SendSkbEntry         = "udp_v6_send_skb_entry"
	captureEventsProgUdpV6SendSkbExit          = "udp_v6_send_skb_exit"
	captureEventsVarEmitDnsSent                = "emit_dns_sent"
	captureEventsVarEmitDnsServer              = "emit_dns_server"
	captureEventsVarEmitDnsTcpMessages         = "emit_dns_tcp_messages"
	captureEventsVarEmitHttpMessages           = "emit_http_messages"
	captureEventsVarEmitTlsPlaintext           = "emit_tls_plaintext"
	captureEventsVarEmitUdpEvents              = "emit_udp_events"
	captureEventsVarHttpMessageLimit           = "http_message_limit"
	captureEventsVarHttpPayloadLimit           = "http_payload_limit"
	captureEventsVarHttpPort                   = "http_port"
	captureEventsVarMysqlPort                  = "mysql_port"
	captureEventsVarTcpLengthFallback          = "tcp_length_fallback"
	captureEventsVarTcpStatePort               = "tcp_state_port"
	captureEventsVarUnusedHttpRecord           = "unused_http_record"
	captureEventsVarUprobeArch                 = "uprobe_arch"
)

// loadCaptureEvents returns the embedded CollectionSpec for captureEvents.
func loadCaptureEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load captureEvents: %w", err)
	}

	return spec, err
}

// loadCaptureEventsObjects loads captureEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*captureEventsObjects
//	*captureEventsPrograms
//	*captureEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCaptureEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadCaptureEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// captureEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsSpecs struct {
	captureEventsProgramSpecs
	captureEventsMapSpecs
	captureEventsVariableSpecs
}

// captureEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsProgramSpecs struct {
	GoTlsArm64CloseEntry      *ebpf.ProgramSpec `ebpf:"go_tls_arm64_close_entry"`
	GoTlsArm64ReadEntry       *ebpf.ProgramSpec `ebpf:"go_tls_arm64_read_entry"`
	GoTlsArm64ReadExit        *ebpf.ProgramSpec `ebpf:"go_tls_arm64_read_exit"`
	GoTlsArm64WriteEntry      *ebpf.ProgramSpec `ebpf:"go_tls_arm64_write_entry"`
	GoTlsArm64WriteExit       *ebpf.ProgramSpec `ebpf:"go_tls_arm64_write_exit"`
	GoTlsCloseEntry           *ebpf.ProgramSpec `ebpf:"go_tls_close_entry"`
	GoTlsReadEntry            *ebpf.ProgramSpec `ebpf:"go_tls_read_entry"`
	GoTlsReadExit             *ebpf.ProgramSpec `ebpf:"go_tls_read_exit"`
	GoTlsWriteEntry           *ebpf.ProgramSpec `ebpf:"go_tls_write_entry"`
	GoTlsWriteExit            *ebpf.ProgramSpec `ebpf:"go_tls_write_exit"`
	HttpTcpDestroySock        *ebpf.ProgramSpec `ebpf:"http_tcp_destroy_sock"`
	InetCskAcceptEntry        *ebpf.ProgramSpec `ebpf:"inet_csk_accept_entry"`
	InetCskAcceptExit         *ebpf.ProgramSpec `ebpf:"inet_csk_accept_exit"`
	InetCskAcceptExitLegacy   *ebpf.ProgramSpec `ebpf:"inet_csk_accept_exit_legacy"`
	InetSockSetState          *ebpf.ProgramSpec `ebpf:"inet_sock_set_state"`
	InetStreamConnectEntry    *ebpf.ProgramSpec `ebpf:"inet_stream_connect_entry"`
	MbedReadEntry             *ebpf.ProgramSpec `ebpf:"mbed_read_entry"`
	MbedWriteEntry            *ebpf.ProgramSpec `ebpf:"mbed_write_entry"`
	NssAcceptEntry            *ebpf.ProgramSpec `ebpf:"nss_accept_entry"`
	NssCloseEntry             *ebpf.ProgramSpec `ebpf:"nss_close_entry"`
	NssControlExit            *ebpf.ProgramSpec `ebpf:"nss_control_exit"`
	NssDefaultEntry           *ebpf.ProgramSpec `ebpf:"nss_default_entry"`
	NssImportEntry            *ebpf.ProgramSpec `ebpf:"nss_import_entry"`
	NssIoExit                 *ebpf.ProgramSpec `ebpf:"nss_io_exit"`
	NssOptionEntry            *ebpf.ProgramSpec `ebpf:"nss_option_entry"`
	NssReadEntry              *ebpf.ProgramSpec `ebpf:"nss_read_entry"`
	NssRecvEntry              *ebpf.ProgramSpec `ebpf:"nss_recv_entry"`
	NssWriteEntry             *ebpf.ProgramSpec `ebpf:"nss_write_entry"`
	RustlsExit                *ebpf.ProgramSpec `ebpf:"rustls_exit"`
	SkbConsumeUdpEntry        *ebpf.ProgramSpec `ebpf:"skb_consume_udp_entry"`
	SslFreeEntry              *ebpf.ProgramSpec `ebpf:"ssl_free_entry"`
	SslReadEntry              *ebpf.ProgramSpec `ebpf:"ssl_read_entry"`
	SslReadExEntry            *ebpf.ProgramSpec `ebpf:"ssl_read_ex_entry"`
	SslReadExExit             *ebpf.ProgramSpec `ebpf:"ssl_read_ex_exit"`
	SslReadExit               *ebpf.ProgramSpec `ebpf:"ssl_read_exit"`
	SslWriteEntry             *ebpf.ProgramSpec `ebpf:"ssl_write_entry"`
	SslWriteExEntry           *ebpf.ProgramSpec `ebpf:"ssl_write_ex_entry"`
	SslWriteExExit            *ebpf.ProgramSpec `ebpf:"ssl_write_ex_exit"`
	SslWriteExit              *ebpf.ProgramSpec `ebpf:"ssl_write_exit"`
	TcpCleanupRbufEntry       *ebpf.ProgramSpec `ebpf:"tcp_cleanup_rbuf_entry"`
	TcpCreateOpenreqChildExit *ebpf.ProgramSpec `ebpf:"tcp_create_openreq_child_exit"`
	TcpDestroySock            *ebpf.ProgramSpec `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset           *ebpf.ProgramSpec `ebpf:"tcp_receive_reset"`
	TcpRecvLength             *ebpf.ProgramSpec `ebpf:"tcp_recv_length"`
	TcpRecvmsgEntry           *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_entry"`
	TcpRecvmsgExit            *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_exit"`
	TcpRecvmsgExitLegacy      *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_exit_legacy"`
	TcpRetransmitSkb          *ebpf.ProgramSpec `ebpf:"tcp_retransmit_skb"`
	TcpSendLength             *ebpf.ProgramSpec `ebpf:"tcp_send_length"`
	TcpSendReset              *ebpf.ProgramSpec `ebpf:"tcp_send_reset"`
	TcpSendmsgEntry           *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_entry"`
	TcpSendmsgExit            *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_exit"`
	UdpEnqueueEntry           *ebpf.ProgramSpec `ebpf:"udp_enqueue_entry"`
	UdpSendSkbEntry           *ebpf.ProgramSpec `ebpf:"udp_send_skb_entry"`
	UdpSendSkbExit            *ebpf.ProgramSpec `ebpf:"udp_send_skb_exit"`
	UdpV6SendSkbEntry         *ebpf.ProgramSpec `ebpf:"udp_v6_send_skb_entry"`
	UdpV6SendSkbExit          *ebpf.ProgramSpec `ebpf:"udp_v6_send_skb_exit"`
}

// captureEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsMapSpecs struct {
	AnnouncedOwners  *ebpf.MapSpec `ebpf:"announced_owners"`
	DnsArrivals      *ebpf.MapSpec `ebpf:"dns_arrivals"`
	DnsQueryPending  *ebpf.MapSpec `ebpf:"dns_query_pending"`
	DnsScratch       *ebpf.MapSpec `ebpf:"dns_scratch"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	GoTlsPending     *ebpf.MapSpec `ebpf:"go_tls_pending"`
	GoTlsWrites      *ebpf.MapSpec `ebpf:"go_tls_writes"`
	HttpCursors      *ebpf.MapSpec `ebpf:"http_cursors"`
	HttpRecvPending  *ebpf.MapSpec `ebpf:"http_recv_pending"`
	HttpScratch      *ebpf.MapSpec `ebpf:"http_scratch"`
	HttpSendPending  *ebpf.MapSpec `ebpf:"http_send_pending"`
	HttpStreams      *ebpf.MapSpec `ebpf:"http_streams"`
	LostEvents       *ebpf.MapSpec `ebpf:"lost_events"`
	LostLines        *ebpf.MapSpec `ebpf:"lost_lines"`
	MysqlSendPending *ebpf.MapSpec `ebpf:"mysql_send_pending"`
	NssConfigs       *ebpf.MapSpec `ebpf:"nss_configs"`
	NssControlCalls  *ebpf.MapSpec `ebpf:"nss_control_calls"`
	NssDefaults      *ebpf.MapSpec `ebpf:"nss_defaults"`
	NssIoCalls       *ebpf.MapSpec `ebpf:"nss_io_calls"`
	SockOwners       *ebpf.MapSpec `ebpf:"sock_owners"`
	SslPending       *ebpf.MapSpec `ebpf:"ssl_pending"`
	SslSocks         *ebpf.MapSpec `ebpf:"ssl_socks"`
	TcpDiagnostics   *ebpf.MapSpec `ebpf:"tcp_diagnostics"`
	TcpEstablishedAt *ebpf.MapSpec `ebpf:"tcp_established_at"`
	TcpLengthPending *ebpf.MapSpec `ebpf:"tcp_length_pending"`
	TlsPrefixes      *ebpf.MapSpec `ebpf:"tls_prefixes"`
	TlsUnmapped      *ebpf.MapSpec `ebpf:"tls_unmapped"`
	UdpSendPending   *ebpf.MapSpec `ebpf:"udp_send_pending"`
}

// captureEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsVariableSpecs struct {
	EmitDnsSent        *ebpf.VariableSpec `ebpf:"emit_dns_sent"`
	EmitDnsServer      *ebpf.VariableSpec `ebpf:"emit_dns_server"`
	EmitDnsTcpMessages *ebpf.VariableSpec `ebpf:"emit_dns_tcp_messages"`
	EmitHttpMessages   *ebpf.VariableSpec `ebpf:"emit_http_messages"`
	EmitTlsPlaintext   *ebpf.VariableSpec `ebpf:"emit_tls_plaintext"`
	EmitUdpEvents      *ebpf.VariableSpec `ebpf:"emit_udp_events"`
	HttpMessageLimit   *ebpf.VariableSpec `ebpf:"http_message_limit"`
	HttpPayloadLimit   *ebpf.VariableSpec `ebpf:"http_payload_limit"`
	HttpPort           *ebpf.VariableSpec `ebpf:"http_port"`
	MysqlPort          *ebpf.VariableSpec `ebpf:"mysql_port"`
	TcpLengthFallback  *ebpf.VariableSpec `ebpf:"tcp_length_fallback"`
	TcpStatePort       *ebpf.VariableSpec `ebpf:"tcp_state_port"`
	UnusedHttpRecord   *ebpf.VariableSpec `ebpf:"unused_http_record"`
	UprobeArch         *ebpf.VariableSpec `ebpf:"uprobe_arch"`
}

// captureEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsObjects struct {
	captureEventsPrograms
	captureEventsMaps
	captureEventsVariables
}

func (o *captureEventsObjects) Close() error {
	return _CaptureEventsClose(
		&o.captureEventsPrograms,
		&o.captureEventsMaps,
	)
}

// captureEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsMaps struct {
	AnnouncedOwners  *ebpf.Map `ebpf:"announced_owners"`
	DnsArrivals      *ebpf.Map `ebpf:"dns_arrivals"`
	DnsQueryPending  *ebpf.Map `ebpf:"dns_query_pending"`
	DnsScratch       *ebpf.Map `ebpf:"dns_scratch"`
	Events           *ebpf.Map `ebpf:"events"`
	GoTlsPending     *ebpf.Map `ebpf:"go_tls_pending"`
	GoTlsWrites      *ebpf.Map `ebpf:"go_tls_writes"`
	HttpCursors      *ebpf.Map `ebpf:"http_cursors"`
	HttpRecvPending  *ebpf.Map `ebpf:"http_recv_pending"`
	HttpScratch      *ebpf.Map `ebpf:"http_scratch"`
	HttpSendPending  *ebpf.Map `ebpf:"http_send_pending"`
	HttpStreams      *ebpf.Map `ebpf:"http_streams"`
	LostEvents       *ebpf.Map `ebpf:"lost_events"`
	LostLines        *ebpf.Map `ebpf:"lost_lines"`
	MysqlSendPending *ebpf.Map `ebpf:"mysql_send_pending"`
	NssConfigs       *ebpf.Map `ebpf:"nss_configs"`
	NssControlCalls  *ebpf.Map `ebpf:"nss_control_calls"`
	NssDefaults      *ebpf.Map `ebpf:"nss_defaults"`
	NssIoCalls       *ebpf.Map `ebpf:"nss_io_calls"`
	SockOwners       *ebpf.Map `ebpf:"sock_owners"`
	SslPending       *ebpf.Map `ebpf:"ssl_pending"`
	SslSocks         *ebpf.Map `ebpf:"ssl_socks"`
	TcpDiagnostics   *ebpf.Map `ebpf:"tcp_diagnostics"`
	TcpEstablishedAt *ebpf.Map `ebpf:"tcp_established_at"`
	TcpLengthPending *ebpf.Map `ebpf:"tcp_length_pending"`
	TlsPrefixes      *ebpf.Map `ebpf:"tls_prefixes"`
	TlsUnmapped      *ebpf.Map `ebpf:"tls_unmapped"`
	UdpSendPending   *ebpf.Map `ebpf:"udp_send_pending"`
}

func (m *captureEventsMaps) Close() error {
	return _CaptureEventsClose(
		m.AnnouncedOwners,
		m.DnsArrivals,
		m.DnsQueryPending,
		m.DnsScratch,
		m.Events,
		m.GoTlsPending,
		m.GoTlsWrites,
		m.HttpCursors,
		m.HttpRecvPending,
		m.HttpScratch,
		m.HttpSendPending,
		m.HttpStreams,
		m.LostEvents,
		m.LostLines,
		m.MysqlSendPending,
		m.NssConfigs,
		m.NssControlCalls,
		m.NssDefaults,
		m.NssIoCalls,
		m.SockOwners,
		m.SslPending,
		m.SslSocks,
		m.TcpDiagnostics,
		m.TcpEstablishedAt,
		m.TcpLengthPending,
		m.TlsPrefixes,
		m.TlsUnmapped,
		m.UdpSendPending,
	)
}

// captureEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsVariables struct {
	EmitDnsSent        *ebpf.Variable `ebpf:"emit_dns_sent"`
	EmitDnsServer      *ebpf.Variable `ebpf:"emit_dns_server"`
	EmitDnsTcpMessages *ebpf.Variable `ebpf:"emit_dns_tcp_messages"`
	EmitHttpMessages   *ebpf.Variable `ebpf:"emit_http_messages"`
	EmitTlsPlaintext   *ebpf.Variable `ebpf:"emit_tls_plaintext"`
	EmitUdpEvents      *ebpf.Variable `ebpf:"emit_udp_events"`
	HttpMessageLimit   *ebpf.Variable `ebpf:"http_message_limit"`
	HttpPayloadLimit   *ebpf.Variable `ebpf:"http_payload_limit"`
	HttpPort           *ebpf.Variable `ebpf:"http_port"`
	MysqlPort          *ebpf.Variable `ebpf:"mysql_port"`
	TcpLengthFallback  *ebpf.Variable `ebpf:"tcp_length_fallback"`
	TcpStatePort       *ebpf.Variable `ebpf:"tcp_state_port"`
	UnusedHttpRecord   *ebpf.Variable `ebpf:"unused_http_record"`
	UprobeArch         *ebpf.Variable `ebpf:"uprobe_arch"`
}

// captureEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsPrograms struct {
	GoTlsArm64CloseEntry      *ebpf.Program `ebpf:"go_tls_arm64_close_entry"`
	GoTlsArm64ReadEntry       *ebpf.Program `ebpf:"go_tls_arm64_read_entry"`
	GoTlsArm64ReadExit        *ebpf.Program `ebpf:"go_tls_arm64_read_exit"`
	GoTlsArm64WriteEntry      *ebpf.Program `ebpf:"go_tls_arm64_write_entry"`
	GoTlsArm64WriteExit       *ebpf.Program `ebpf:"go_tls_arm64_write_exit"`
	GoTlsCloseEntry           *ebpf.Program `ebpf:"go_tls_close_entry"`
	GoTlsReadEntry            *ebpf.Program `ebpf:"go_tls_read_entry"`
	GoTlsReadExit             *ebpf.Program `ebpf:"go_tls_read_exit"`
	GoTlsWriteEntry           *ebpf.Program `ebpf:"go_tls_write_entry"`
	GoTlsWriteExit            *ebpf.Program `ebpf:"go_tls_write_exit"`
	HttpTcpDestroySock        *ebpf.Program `ebpf:"http_tcp_destroy_sock"`
	InetCskAcceptEntry        *ebpf.Program `ebpf:"inet_csk_accept_entry"`
	InetCskAcceptExit         *ebpf.Program `ebpf:"inet_csk_accept_exit"`
	InetCskAcceptExitLegacy   *ebpf.Program `ebpf:"inet_csk_accept_exit_legacy"`
	InetSockSetState          *ebpf.Program `ebpf:"inet_sock_set_state"`
	InetStreamConnectEntry    *ebpf.Program `ebpf:"inet_stream_connect_entry"`
	MbedReadEntry             *ebpf.Program `ebpf:"mbed_read_entry"`
	MbedWriteEntry            *ebpf.Program `ebpf:"mbed_write_entry"`
	NssAcceptEntry            *ebpf.Program `ebpf:"nss_accept_entry"`
	NssCloseEntry             *ebpf.Program `ebpf:"nss_close_entry"`
	NssControlExit            *ebpf.Program `ebpf:"nss_control_exit"`
	NssDefaultEntry           *ebpf.Program `ebpf:"nss_default_entry"`
	NssImportEntry            *ebpf.Program `ebpf:"nss_import_entry"`
	NssIoExit                 *ebpf.Program `ebpf:"nss_io_exit"`
	NssOptionEntry            *ebpf.Program `ebpf:"nss_option_entry"`
	NssReadEntry              *ebpf.Program `ebpf:"nss_read_entry"`
	NssRecvEntry              *ebpf.Program `ebpf:"nss_recv_entry"`
	NssWriteEntry             *ebpf.Program `ebpf:"nss_write_entry"`
	RustlsExit                *ebpf.Program `ebpf:"rustls_exit"`
	SkbConsumeUdpEntry        *ebpf.Program `ebpf:"skb_consume_udp_entry"`
	SslFreeEntry              *ebpf.Program `ebpf:"ssl_free_entry"`
	SslReadEntry              *ebpf.Program `ebpf:"ssl_read_entry"`
	SslReadExEntry            *ebpf.Program `ebpf:"ssl_read_ex_entry"`
	SslReadExExit             *ebpf.Program `ebpf:"ssl_read_ex_exit"`
	SslReadExit               *ebpf.Program `ebpf:"ssl_read_exit"`
	SslWriteEntry             *ebpf.Program `ebpf:"ssl_write_entry"`
	SslWriteExEntry           *ebpf.Program `ebpf:"ssl_write_ex_entry"`
	SslWriteExExit            *ebpf.Program `ebpf:"ssl_write_ex_exit"`
	SslWriteExit              *ebpf.Program `ebpf:"ssl_write_exit"`
	TcpCleanupRbufEntry       *ebpf.Program `ebpf:"tcp_cleanup_rbuf_entry"`
	TcpCreateOpenreqChildExit *ebpf.Program `ebpf:"tcp_create_openreq_child_exit"`
	TcpDestroySock            *ebpf.Program `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset           *ebpf.Program `ebpf:"tcp_receive_reset"`
	TcpRecvLength             *ebpf.Program `ebpf:"tcp_recv_length"`
	TcpRecvmsgEntry           *ebpf.Program `ebpf:"tcp_recvmsg_entry"`
	TcpRecvmsgExit            *ebpf.Program `ebpf:"tcp_recvmsg_exit"`
	TcpRecvmsgExitLegacy      *ebpf.Program `ebpf:"tcp_recvmsg_exit_legacy"`
	TcpRetransmitSkb          *ebpf.Program `ebpf:"tcp_retransmit_skb"`
	TcpSendLength             *ebpf.Program `ebpf:"tcp_send_length"`
	TcpSendReset              *ebpf.Program `ebpf:"tcp_send_reset"`
	TcpSendmsgEntry           *ebpf.Program `ebpf:"tcp_sendmsg_entry"`
	TcpSendmsgExit            *ebpf.Program `ebpf:"tcp_sendmsg_exit"`
	UdpEnqueueEntry           *ebpf.Program `ebpf:"udp_enqueue_entry"`
	UdpSendSkbEntry           *ebpf.Program `ebpf:"udp_send_skb_entry"`
	UdpSendSkbExit            *ebpf.Program `ebpf:"udp_send_skb_exit"`
	UdpV6SendSkbEntry         *ebpf.Program `ebpf:"udp_v6_send_skb_entry"`
	UdpV6SendSkbExit          *ebpf.Program `ebpf:"udp_v6_send_skb_exit"`
}

func (p *captureEventsPrograms) Close() error {
	return _CaptureEventsClose(
		p.GoTlsArm64CloseEntry,
		p.GoTlsArm64ReadEntry,
		p.GoTlsArm64ReadExit,
		p.GoTlsArm64WriteEntry,
		p.GoTlsArm64WriteExit,
		p.GoTlsCloseEntry,
		p.GoTlsReadEntry,
		p.GoTlsReadExit,
		p.GoTlsWriteEntry,
		p.GoTlsWriteExit,
		p.HttpTcpDestroySock,
		p.InetCskAcceptEntry,
		p.InetCskAcceptExit,
		p.InetCskAcceptExitLegacy,
		p.InetSockSetState,
		p.InetStreamConnectEntry,
		p.MbedReadEntry,
		p.MbedWriteEntry,
		p.NssAcceptEntry,
		p.NssCloseEntry,
		p.NssControlExit,
		p.NssDefaultEntry,
		p.NssImportEntry,
		p.NssIoExit,
		p.NssOptionEntry,
		p.NssReadEntry,
		p.NssRecvEntry,
		p.NssWriteEntry,
		p.RustlsExit,
		p.SkbConsumeUdpEntry,
		p.SslFreeEntry,
		p.SslReadEntry,
		p.SslReadExEntry,
		p.SslReadExExit,
		p.SslReadExit,
		p.SslWriteEntry,
		p.SslWriteExEntry,
		p.SslWriteExExit,
		p.SslWriteExit,
		p.TcpCleanupRbufEntry,
		p.TcpCreateOpenreqChildExit,
		p.TcpDestroySock,
		p.TcpReceiveReset,
		p.TcpRecvLength,
		p.TcpRecvmsgEntry,
		p.TcpRecvmsgExit,
		p.TcpRecvmsgExitLegacy,
		p.TcpRetransmitSkb,
		p.TcpSendLength,
		p.TcpSendReset,
		p.TcpSendmsgEntry,
		p.TcpSendmsgExit,
		p.UdpEnqueueEntry,
		p.UdpSendSkbEntry,
		p.UdpSendSkbExit,
		p.UdpV6SendSkbEntry,
		p.UdpV6SendSkbExit,
	)
}

func _CaptureEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed captureevents_bpfeb.o
var _CaptureEventsBytes []byte
