// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type captureEventsDnsRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	CgroupId    uint64
	ArrivalNs   uint64
	Skaddr      uint64
	Len         uint32
	Family      uint16
	Direction   uint8
	Transport   uint8
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	Comm        [16]int8
	Payload     [1024]uint8
	_           [4]byte
}

type captureEventsHttpRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	EventType   uint32
	Pid         uint32
	CgroupId    uint64
	Skaddr      uint64
	Len         uint32
	Family      uint16
	Direction   uint8
	Reserved    uint8
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	Comm        [16]int8
	Payload     [512]uint8
	_           [4]byte
}

type captureEventsHttpRecvPending struct {
	_      structs.HostLayout
	Skaddr uint64
	Buffer uint64
	Limit  uint64
}

type captureEventsSockOwner struct {
	_        structs.HostLayout
	CgroupId uint64
	Pid      uint32
	Comm     [16]int8
	_        [4]byte
}

type captureEventsUdpSendPending struct {
	_           structs.HostLayout
	Skaddr      uint64
	Bytes       uint64
	Family      uint16
	Sport       uint16
	Dport       uint16
	Source      [16]uint8
	Destination [16]uint8
	_           [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	captureEventsMapAnnouncedOwners            = "announced_owners"
	captureEventsMapDnsArrivals                = "dns_arrivals"
	captureEventsMapDnsQueryPending            = "dns_query_pending"
	captureEventsMapDnsScratch                 = "dns_scratch"
	captureEventsMapEvents                     = "events"
	captureEventsMapHttpRecvPending            = "http_recv_pending"
	captureEventsMapLostEvents                 = "lost_events"
	captureEventsMapSockOwners                 = "sock_owners"
	captureEventsMapUdpSendPending             = "udp_send_pending"
	captureEventsProgInetCskAcceptEntry        = "inet_csk_accept_entry"
	captureEventsProgInetSockSetState          = "inet_sock_set_state"
	captureEventsProgSkbConsumeUdpEntry        = "skb_consume_udp_entry"
	captureEventsProgTcpCreateOpenreqChildExit = "tcp_create_openreq_child_exit"
	captureEventsProgTcpDestroySock            = "tcp_destroy_sock"
	captureEventsProgTcpReceiveReset           = "tcp_receive_reset"
	captureEventsProgTcpRecvLength             = "tcp_recv_length"
	captureEventsProgTcpRecvmsgEntry           = "tcp_recvmsg_entry"
	captureEventsProgTcpRecvmsgExit            = "tcp_recvmsg_exit"
	captureEventsProgTcpRetransmitSkb          = "tcp_retransmit_skb"
	captureEventsProgTcpSendLength             = "tcp_send_length"
	captureEventsProgTcpSendReset              = "tcp_send_reset"
	captureEventsProgTcpSendmsgEntry           = "tcp_sendmsg_entry"
	captureEventsProgUdpEnqueueEntry           = "udp_enqueue_entry"
	captureEventsProgUdpSendSkbEntry           = "udp_send_skb_entry"
	captureEventsProgUdpSendSkbExit            = "udp_send_skb_exit"
	captureEventsProgUdpV6SendSkbEntry         = "udp_v6_send_skb_entry"
	captureEventsProgUdpV6SendSkbExit          = "udp_v6_send_skb_exit"
	captureEventsVarEmitDnsSent                = "emit_dns_sent"
	captureEventsVarEmitDnsServer              = "emit_dns_server"
	captureEventsVarEmitDnsTcpMessages         = "emit_dns_tcp_messages"
	captureEventsVarEmitHttpMessages           = "emit_http_messages"
	captureEventsVarEmitUdpEvents              = "emit_udp_events"
	captureEventsVarTcpStatePort               = "tcp_state_port"
	captureEventsVarUnusedHttpRecord           = "unused_http_record"
)

// loadCaptureEvents returns the embedded CollectionSpec for captureEvents.
func loadCaptureEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load captureEvents: %w", err)
	}

	return spec, err
}

// loadCaptureEventsObjects loads captureEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*captureEventsObjects
//	*captureEventsPrograms
//	*captureEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCaptureEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadCaptureEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// captureEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsSpecs struct {
	captureEventsProgramSpecs
	captureEventsMapSpecs
	captureEventsVariableSpecs
}

// captureEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsProgramSpecs struct {
	InetCskAcceptEntry        *ebpf.ProgramSpec `ebpf:"inet_csk_accept_entry"`
	InetSockSetState          *ebpf.ProgramSpec `ebpf:"inet_sock_set_state"`
	SkbConsumeUdpEntry        *ebpf.ProgramSpec `ebpf:"skb_consume_udp_entry"`
	TcpCreateOpenreqChildExit *ebpf.ProgramSpec `ebpf:"tcp_create_openreq_child_exit"`
	TcpDestroySock            *ebpf.ProgramSpec `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset           *ebpf.ProgramSpec `ebpf:"tcp_receive_reset"`
	TcpRecvLength             *ebpf.ProgramSpec `ebpf:"tcp_recv_length"`
	TcpRecvmsgEntry           *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_entry"`
	TcpRecvmsgExit            *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_exit"`
	TcpRetransmitSkb          *ebpf.ProgramSpec `ebpf:"tcp_retransmit_skb"`
	TcpSendLength             *ebpf.ProgramSpec `ebpf:"tcp_send_length"`
	TcpSendReset              *ebpf.ProgramSpec `ebpf:"tcp_send_reset"`
	TcpSendmsgEntry           *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_entry"`
	UdpEnqueueEntry           *ebpf.ProgramSpec `ebpf:"udp_enqueue_entry"`
	UdpSendSkbEntry           *ebpf.ProgramSpec `ebpf:"udp_send_skb_entry"`
	UdpSendSkbExit            *ebpf.ProgramSpec `ebpf:"udp_send_skb_exit"`
	UdpV6SendSkbEntry         *ebpf.ProgramSpec `ebpf:"udp_v6_send_skb_entry"`
	UdpV6SendSkbExit          *ebpf.ProgramSpec `ebpf:"udp_v6_send_skb_exit"`
}

// captureEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsMapSpecs struct {
	AnnouncedOwners *ebpf.MapSpec `ebpf:"announced_owners"`
	DnsArrivals     *ebpf.MapSpec `ebpf:"dns_arrivals"`
	DnsQueryPending *ebpf.MapSpec `ebpf:"dns_query_pending"`
	DnsScratch      *ebpf.MapSpec `ebpf:"dns_scratch"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	HttpRecvPending *ebpf.MapSpec `ebpf:"http_recv_pending"`
	LostEvents      *ebpf.MapSpec `ebpf:"lost_events"`
	SockOwners      *ebpf.MapSpec `ebpf:"sock_owners"`
	UdpSendPending  *ebpf.MapSpec `ebpf:"udp_send_pending"`
}

// captureEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsVariableSpecs struct {
	EmitDnsSent        *ebpf.VariableSpec `ebpf:"emit_dns_sent"`
	EmitDnsServer      *ebpf.VariableSpec `ebpf:"emit_dns_server"`
	EmitDnsTcpMessages *ebpf.VariableSpec `ebpf:"emit_dns_tcp_messages"`
	EmitHttpMessages   *ebpf.VariableSpec `ebpf:"emit_http_messages"`
	EmitUdpEvents      *ebpf.VariableSpec `ebpf:"emit_udp_events"`
	TcpStatePort       *ebpf.VariableSpec `ebpf:"tcp_state_port"`
	UnusedHttpRecord   *ebpf.VariableSpec `ebpf:"unused_http_record"`
}

// captureEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsObjects struct {
	captureEventsPrograms
	captureEventsMaps
	captureEventsVariables
}

func (o *captureEventsObjects) Close() error {
	return _CaptureEventsClose(
		&o.captureEventsPrograms,
		&o.captureEventsMaps,
	)
}

// captureEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsMaps struct {
	AnnouncedOwners *ebpf.Map `ebpf:"announced_owners"`
	DnsArrivals     *ebpf.Map `ebpf:"dns_arrivals"`
	DnsQueryPending *ebpf.Map `ebpf:"dns_query_pending"`
	DnsScratch      *ebpf.Map `ebpf:"dns_scratch"`
	Events          *ebpf.Map `ebpf:"events"`
	HttpRecvPending *ebpf.Map `ebpf:"http_recv_pending"`
	LostEvents      *ebpf.Map `ebpf:"lost_events"`
	SockOwners      *ebpf.Map `ebpf:"sock_owners"`
	UdpSendPending  *ebpf.Map `ebpf:"udp_send_pending"`
}

func (m *captureEventsMaps) Close() error {
	return _CaptureEventsClose(
		m.AnnouncedOwners,
		m.DnsArrivals,
		m.DnsQueryPending,
		m.DnsScratch,
		m.Events,
		m.HttpRecvPending,
		m.LostEvents,
		m.SockOwners,
		m.UdpSendPending,
	)
}

// captureEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsVariables struct {
	EmitDnsSent        *ebpf.Variable `ebpf:"emit_dns_sent"`
	EmitDnsServer      *ebpf.Variable `ebpf:"emit_dns_server"`
	EmitDnsTcpMessages *ebpf.Variable `ebpf:"emit_dns_tcp_messages"`
	EmitHttpMessages   *ebpf.Variable `ebpf:"emit_http_messages"`
	EmitUdpEvents      *ebpf.Variable `ebpf:"emit_udp_events"`
	TcpStatePort       *ebpf.Variable `ebpf:"tcp_state_port"`
	UnusedHttpRecord   *ebpf.Variable `ebpf:"unused_http_record"`
}

// captureEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsPrograms struct {
	InetCskAcceptEntry        *ebpf.Program `ebpf:"inet_csk_accept_entry"`
	InetSockSetState          *ebpf.Program `ebpf:"inet_sock_set_state"`
	SkbConsumeUdpEntry        *ebpf.Program `ebpf:"skb_consume_udp_entry"`
	TcpCreateOpenreqChildExit *ebpf.Program `ebpf:"tcp_create_openreq_child_exit"`
	TcpDestroySock            *ebpf.Program `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset           *ebpf.Program `ebpf:"tcp_receive_reset"`
	TcpRecvLength             *ebpf.Program `ebpf:"tcp_recv_length"`
	TcpRecvmsgEntry           *ebpf.Program `ebpf:"tcp_recvmsg_entry"`
	TcpRecvmsgExit            *ebpf.Program `ebpf:"tcp_recvmsg_exit"`
	TcpRetransmitSkb          *ebpf.Program `ebpf:"tcp_retransmit_skb"`
	TcpSendLength             *ebpf.Program `ebpf:"tcp_send_length"`
	TcpSendReset              *ebpf.Program `ebpf:"tcp_send_reset"`
	TcpSendmsgEntry           *ebpf.Program `ebpf:"tcp_sendmsg_entry"`
	UdpEnqueueEntry           *ebpf.Program `ebpf:"udp_enqueue_entry"`
	UdpSendSkbEntry           *ebpf.Program `ebpf:"udp_send_skb_entry"`
	UdpSendSkbExit            *ebpf.Program `ebpf:"udp_send_skb_exit"`
	UdpV6SendSkbEntry         *ebpf.Program `ebpf:"udp_v6_send_skb_entry"`
	UdpV6SendSkbExit          *ebpf.Program `ebpf:"udp_v6_send_skb_exit"`
}

func (p *captureEventsPrograms) Close() error {
	return _CaptureEventsClose(
		p.InetCskAcceptEntry,
		p.InetSockSetState,
		p.SkbConsumeUdpEntry,
		p.TcpCreateOpenreqChildExit,
		p.TcpDestroySock,
		p.TcpReceiveReset,
		p.TcpRecvLength,
		p.TcpRecvmsgEntry,
		p.TcpRecvmsgExit,
		p.TcpRetransmitSkb,
		p.TcpSendLength,
		p.TcpSendReset,
		p.TcpSendmsgEntry,
		p.UdpEnqueueEntry,
		p.UdpSendSkbEntry,
		p.UdpSendSkbExit,
		p.UdpV6SendSkbEntry,
		p.UdpV6SendSkbExit,
	)
}

func _CaptureEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed captureevents_bpfel.o
var _CaptureEventsBytes []byte
