// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	captureEventsMapEvents              = "events"
	captureEventsMapLostEvents          = "lost_events"
	captureEventsProgInetSockSetState   = "inet_sock_set_state"
	captureEventsProgSkbConsumeUdpEntry = "skb_consume_udp_entry"
	captureEventsProgTcpDestroySock     = "tcp_destroy_sock"
	captureEventsProgTcpReceiveReset    = "tcp_receive_reset"
	captureEventsProgTcpRecvLength      = "tcp_recv_length"
	captureEventsProgTcpRetransmitSkb   = "tcp_retransmit_skb"
	captureEventsProgTcpSendLength      = "tcp_send_length"
	captureEventsProgTcpSendReset       = "tcp_send_reset"
	captureEventsProgUdpSendmsgExit     = "udp_sendmsg_exit"
	captureEventsProgUdpv6SendmsgExit   = "udpv6_sendmsg_exit"
)

// loadCaptureEvents returns the embedded CollectionSpec for captureEvents.
func loadCaptureEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load captureEvents: %w", err)
	}

	return spec, err
}

// loadCaptureEventsObjects loads captureEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*captureEventsObjects
//	*captureEventsPrograms
//	*captureEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCaptureEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadCaptureEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// captureEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsSpecs struct {
	captureEventsProgramSpecs
	captureEventsMapSpecs
	captureEventsVariableSpecs
}

// captureEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsProgramSpecs struct {
	InetSockSetState   *ebpf.ProgramSpec `ebpf:"inet_sock_set_state"`
	SkbConsumeUdpEntry *ebpf.ProgramSpec `ebpf:"skb_consume_udp_entry"`
	TcpDestroySock     *ebpf.ProgramSpec `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset    *ebpf.ProgramSpec `ebpf:"tcp_receive_reset"`
	TcpRecvLength      *ebpf.ProgramSpec `ebpf:"tcp_recv_length"`
	TcpRetransmitSkb   *ebpf.ProgramSpec `ebpf:"tcp_retransmit_skb"`
	TcpSendLength      *ebpf.ProgramSpec `ebpf:"tcp_send_length"`
	TcpSendReset       *ebpf.ProgramSpec `ebpf:"tcp_send_reset"`
	UdpSendmsgExit     *ebpf.ProgramSpec `ebpf:"udp_sendmsg_exit"`
	Udpv6SendmsgExit   *ebpf.ProgramSpec `ebpf:"udpv6_sendmsg_exit"`
}

// captureEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	LostEvents *ebpf.MapSpec `ebpf:"lost_events"`
}

// captureEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureEventsVariableSpecs struct {
}

// captureEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsObjects struct {
	captureEventsPrograms
	captureEventsMaps
	captureEventsVariables
}

func (o *captureEventsObjects) Close() error {
	return _CaptureEventsClose(
		&o.captureEventsPrograms,
		&o.captureEventsMaps,
	)
}

// captureEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	LostEvents *ebpf.Map `ebpf:"lost_events"`
}

func (m *captureEventsMaps) Close() error {
	return _CaptureEventsClose(
		m.Events,
		m.LostEvents,
	)
}

// captureEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsVariables struct {
}

// captureEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCaptureEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureEventsPrograms struct {
	InetSockSetState   *ebpf.Program `ebpf:"inet_sock_set_state"`
	SkbConsumeUdpEntry *ebpf.Program `ebpf:"skb_consume_udp_entry"`
	TcpDestroySock     *ebpf.Program `ebpf:"tcp_destroy_sock"`
	TcpReceiveReset    *ebpf.Program `ebpf:"tcp_receive_reset"`
	TcpRecvLength      *ebpf.Program `ebpf:"tcp_recv_length"`
	TcpRetransmitSkb   *ebpf.Program `ebpf:"tcp_retransmit_skb"`
	TcpSendLength      *ebpf.Program `ebpf:"tcp_send_length"`
	TcpSendReset       *ebpf.Program `ebpf:"tcp_send_reset"`
	UdpSendmsgExit     *ebpf.Program `ebpf:"udp_sendmsg_exit"`
	Udpv6SendmsgExit   *ebpf.Program `ebpf:"udpv6_sendmsg_exit"`
}

func (p *captureEventsPrograms) Close() error {
	return _CaptureEventsClose(
		p.InetSockSetState,
		p.SkbConsumeUdpEntry,
		p.TcpDestroySock,
		p.TcpReceiveReset,
		p.TcpRecvLength,
		p.TcpRetransmitSkb,
		p.TcpSendLength,
		p.TcpSendReset,
		p.UdpSendmsgExit,
		p.Udpv6SendmsgExit,
	)
}

func _CaptureEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed captureevents_bpfeb.o
var _CaptureEventsBytes []byte
