// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dropEventsDropRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	Location    uint64
	SockIno     uint64
	Reason      uint32
	Len         uint32
	Protocol    uint16
	L4          uint8
	Family      uint8
	Sport       uint16
	Dport       uint16
	Saddr       [16]uint8
	Daddr       [16]uint8
}

type dropEventsDropWindow struct {
	_          structs.HostLayout
	StartNs    uint64
	Sent       uint64
	Suppressed uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	dropEventsMapDropCounts       = "drop_counts"
	dropEventsMapDropWindows      = "drop_windows"
	dropEventsMapEvents           = "events"
	dropEventsMapLostEvents       = "lost_events"
	dropEventsProgKfreeSkb        = "kfree_skb"
	dropEventsVarEventLimit       = "event_limit"
	dropEventsVarFilterReasons    = "filter_reasons"
	dropEventsVarReasonFilter     = "reason_filter"
	dropEventsVarUnusedDropRecord = "unused_drop_record"
)

// loadDropEvents returns the embedded CollectionSpec for dropEvents.
func loadDropEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DropEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dropEvents: %w", err)
	}

	return spec, err
}

// loadDropEventsObjects loads dropEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dropEventsObjects
//	*dropEventsPrograms
//	*dropEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDropEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadDropEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dropEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropEventsSpecs struct {
	dropEventsProgramSpecs
	dropEventsMapSpecs
	dropEventsVariableSpecs
}

// dropEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropEventsProgramSpecs struct {
	KfreeSkb *ebpf.ProgramSpec `ebpf:"kfree_skb"`
}

// dropEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropEventsMapSpecs struct {
	DropCounts  *ebpf.MapSpec `ebpf:"drop_counts"`
	DropWindows *ebpf.MapSpec `ebpf:"drop_windows"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	LostEvents  *ebpf.MapSpec `ebpf:"lost_events"`
}

// dropEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropEventsVariableSpecs struct {
	EventLimit       *ebpf.VariableSpec `ebpf:"event_limit"`
	FilterReasons    *ebpf.VariableSpec `ebpf:"filter_reasons"`
	ReasonFilter     *ebpf.VariableSpec `ebpf:"reason_filter"`
	UnusedDropRecord *ebpf.VariableSpec `ebpf:"unused_drop_record"`
}

// dropEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDropEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropEventsObjects struct {
	dropEventsPrograms
	dropEventsMaps
	dropEventsVariables
}

func (o *dropEventsObjects) Close() error {
	return _DropEventsClose(
		&o.dropEventsPrograms,
		&o.dropEventsMaps,
	)
}

// dropEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDropEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropEventsMaps struct {
	DropCounts  *ebpf.Map `ebpf:"drop_counts"`
	DropWindows *ebpf.Map `ebpf:"drop_windows"`
	Events      *ebpf.Map `ebpf:"events"`
	LostEvents  *ebpf.Map `ebpf:"lost_events"`
}

func (m *dropEventsMaps) Close() error {
	return _DropEventsClose(
		m.DropCounts,
		m.DropWindows,
		m.Events,
		m.LostEvents,
	)
}

// dropEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDropEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropEventsVariables struct {
	EventLimit       *ebpf.Variable `ebpf:"event_limit"`
	FilterReasons    *ebpf.Variable `ebpf:"filter_reasons"`
	ReasonFilter     *ebpf.Variable `ebpf:"reason_filter"`
	UnusedDropRecord *ebpf.Variable `ebpf:"unused_drop_record"`
}

// dropEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDropEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropEventsPrograms struct {
	KfreeSkb *ebpf.Program `ebpf:"kfree_skb"`
}

func (p *dropEventsPrograms) Close() error {
	return _DropEventsClose(
		p.KfreeSkb,
	)
}

func _DropEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dropevents_bpfeb.o
var _DropEventsBytes []byte
