// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ioEventsIoCounters struct {
	_      structs.HostLayout
	Values [5]uint64
}

type ioEventsIoPending struct {
	_        structs.HostLayout
	InsertNs uint64
	IssueNs  uint64
	CgroupId uint64
	Bytes    uint64
	Dev      uint32
	Pid      uint32
	Comm     [16]int8
	Rwbs     [8]int8
	Stage    uint8
	_        [7]byte
}

type ioEventsIoRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	CgroupId    uint64
	Bytes       uint64
	QueueNs     uint64
	ServiceNs   uint64
	TotalNs     uint64
	Dev         uint32
	Pid         uint32
	Comm        [16]int8
	Rwbs        [8]int8
	Attribution uint8
	_           [7]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ioEventsMapCounters         = "counters"
	ioEventsMapEvents           = "events"
	ioEventsMapPending          = "pending"
	ioEventsProgComplete        = "complete"
	ioEventsProgInsert          = "insert"
	ioEventsProgIssue           = "issue"
	ioEventsProgRequeue         = "requeue"
	ioEventsVarMinimumLatencyNs = "minimum_latency_ns"
	ioEventsVarUnusedIoCounters = "unused_io_counters"
	ioEventsVarUnusedIoRecord   = "unused_io_record"
)

// loadIoEvents returns the embedded CollectionSpec for ioEvents.
func loadIoEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IoEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ioEvents: %w", err)
	}

	return spec, err
}

// loadIoEventsObjects loads ioEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ioEventsObjects
//	*ioEventsPrograms
//	*ioEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadIoEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadIoEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ioEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioEventsSpecs struct {
	ioEventsProgramSpecs
	ioEventsMapSpecs
	ioEventsVariableSpecs
}

// ioEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioEventsProgramSpecs struct {
	Complete *ebpf.ProgramSpec `ebpf:"complete"`
	Insert   *ebpf.ProgramSpec `ebpf:"insert"`
	Issue    *ebpf.ProgramSpec `ebpf:"issue"`
	Requeue  *ebpf.ProgramSpec `ebpf:"requeue"`
}

// ioEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioEventsMapSpecs struct {
	Counters *ebpf.MapSpec `ebpf:"counters"`
	Events   *ebpf.MapSpec `ebpf:"events"`
	Pending  *ebpf.MapSpec `ebpf:"pending"`
}

// ioEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ioEventsVariableSpecs struct {
	MinimumLatencyNs *ebpf.VariableSpec `ebpf:"minimum_latency_ns"`
	UnusedIoCounters *ebpf.VariableSpec `ebpf:"unused_io_counters"`
	UnusedIoRecord   *ebpf.VariableSpec `ebpf:"unused_io_record"`
}

// ioEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadIoEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioEventsObjects struct {
	ioEventsPrograms
	ioEventsMaps
	ioEventsVariables
}

func (o *ioEventsObjects) Close() error {
	return _IoEventsClose(
		&o.ioEventsPrograms,
		&o.ioEventsMaps,
	)
}

// ioEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadIoEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioEventsMaps struct {
	Counters *ebpf.Map `ebpf:"counters"`
	Events   *ebpf.Map `ebpf:"events"`
	Pending  *ebpf.Map `ebpf:"pending"`
}

func (m *ioEventsMaps) Close() error {
	return _IoEventsClose(
		m.Counters,
		m.Events,
		m.Pending,
	)
}

// ioEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadIoEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioEventsVariables struct {
	MinimumLatencyNs *ebpf.Variable `ebpf:"minimum_latency_ns"`
	UnusedIoCounters *ebpf.Variable `ebpf:"unused_io_counters"`
	UnusedIoRecord   *ebpf.Variable `ebpf:"unused_io_record"`
}

// ioEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadIoEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type ioEventsPrograms struct {
	Complete *ebpf.Program `ebpf:"complete"`
	Insert   *ebpf.Program `ebpf:"insert"`
	Issue    *ebpf.Program `ebpf:"issue"`
	Requeue  *ebpf.Program `ebpf:"requeue"`
}

func (p *ioEventsPrograms) Close() error {
	return _IoEventsClose(
		p.Complete,
		p.Insert,
		p.Issue,
		p.Requeue,
	)
}

func _IoEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ioevents_bpfel.o
var _IoEventsBytes []byte
