// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type schedEventsOffcpu struct {
	_             structs.HostLayout
	TimestampNs   uint64
	StartBoottime uint64
	CgroupId      uint64
	Comm          [16]int8
	Klass         uint8
	_             [7]byte
}

type schedEventsPending struct {
	_             structs.HostLayout
	TimestampNs   uint64
	StartBoottime uint64
	CgroupId      uint64
	Comm          [16]int8
}

type schedEventsSchedCounters struct {
	_               structs.HostLayout
	LostEvents      uint64
	MapFull         uint64
	Unmatched       uint64
	RepeatedWakeups uint64
	BelowThreshold  uint64
}

type schedEventsSchedRecord struct {
	_             structs.HostLayout
	TimestampNs   uint64
	LatencyNs     uint64
	CgroupId      uint64
	StartBoottime uint64
	Pid           uint32
	Comm          [16]int8
	Kind          uint8
	OffcpuClass   uint8
	Reserved      uint16
}

type schedEventsTaskKey struct {
	_             structs.HostLayout
	Pid           uint32
	_             [4]byte
	StartBoottime uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	schedEventsMapCounters            = "counters"
	schedEventsMapEvents              = "events"
	schedEventsMapOffcpus             = "offcpus"
	schedEventsMapWakeups             = "wakeups"
	schedEventsProgSchedProcessExit   = "sched_process_exit"
	schedEventsProgSchedSwitch        = "sched_switch"
	schedEventsProgSchedWakeup        = "sched_wakeup"
	schedEventsProgSchedWakeupNew     = "sched_wakeup_new"
	schedEventsVarMinimumLatencyNs    = "minimum_latency_ns"
	schedEventsVarUnusedSchedCounters = "unused_sched_counters"
	schedEventsVarUnusedSchedRecord   = "unused_sched_record"
)

// loadSchedEvents returns the embedded CollectionSpec for schedEvents.
func loadSchedEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load schedEvents: %w", err)
	}

	return spec, err
}

// loadSchedEventsObjects loads schedEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*schedEventsObjects
//	*schedEventsPrograms
//	*schedEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSchedEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSchedEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// schedEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedEventsSpecs struct {
	schedEventsProgramSpecs
	schedEventsMapSpecs
	schedEventsVariableSpecs
}

// schedEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedEventsProgramSpecs struct {
	SchedProcessExit *ebpf.ProgramSpec `ebpf:"sched_process_exit"`
	SchedSwitch      *ebpf.ProgramSpec `ebpf:"sched_switch"`
	SchedWakeup      *ebpf.ProgramSpec `ebpf:"sched_wakeup"`
	SchedWakeupNew   *ebpf.ProgramSpec `ebpf:"sched_wakeup_new"`
}

// schedEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedEventsMapSpecs struct {
	Counters *ebpf.MapSpec `ebpf:"counters"`
	Events   *ebpf.MapSpec `ebpf:"events"`
	Offcpus  *ebpf.MapSpec `ebpf:"offcpus"`
	Wakeups  *ebpf.MapSpec `ebpf:"wakeups"`
}

// schedEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type schedEventsVariableSpecs struct {
	MinimumLatencyNs    *ebpf.VariableSpec `ebpf:"minimum_latency_ns"`
	UnusedSchedCounters *ebpf.VariableSpec `ebpf:"unused_sched_counters"`
	UnusedSchedRecord   *ebpf.VariableSpec `ebpf:"unused_sched_record"`
}

// schedEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSchedEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedEventsObjects struct {
	schedEventsPrograms
	schedEventsMaps
	schedEventsVariables
}

func (o *schedEventsObjects) Close() error {
	return _SchedEventsClose(
		&o.schedEventsPrograms,
		&o.schedEventsMaps,
	)
}

// schedEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSchedEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedEventsMaps struct {
	Counters *ebpf.Map `ebpf:"counters"`
	Events   *ebpf.Map `ebpf:"events"`
	Offcpus  *ebpf.Map `ebpf:"offcpus"`
	Wakeups  *ebpf.Map `ebpf:"wakeups"`
}

func (m *schedEventsMaps) Close() error {
	return _SchedEventsClose(
		m.Counters,
		m.Events,
		m.Offcpus,
		m.Wakeups,
	)
}

// schedEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSchedEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedEventsVariables struct {
	MinimumLatencyNs    *ebpf.Variable `ebpf:"minimum_latency_ns"`
	UnusedSchedCounters *ebpf.Variable `ebpf:"unused_sched_counters"`
	UnusedSchedRecord   *ebpf.Variable `ebpf:"unused_sched_record"`
}

// schedEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSchedEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type schedEventsPrograms struct {
	SchedProcessExit *ebpf.Program `ebpf:"sched_process_exit"`
	SchedSwitch      *ebpf.Program `ebpf:"sched_switch"`
	SchedWakeup      *ebpf.Program `ebpf:"sched_wakeup"`
	SchedWakeupNew   *ebpf.Program `ebpf:"sched_wakeup_new"`
}

func (p *schedEventsPrograms) Close() error {
	return _SchedEventsClose(
		p.SchedProcessExit,
		p.SchedSwitch,
		p.SchedWakeup,
		p.SchedWakeupNew,
	)
}

func _SchedEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed schedevents_bpfel.o
var _SchedEventsBytes []byte
