// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type socketEventsSocketCall struct {
	_          structs.HostLayout
	Skaddr     uint64
	PeerSkaddr uint64
	Buffer     uint64
	Limit      uint64
	Iov        uint64
	NrSegs     uint64
	PeerPid    uint32
	EventType  uint32
	Side       uint8
	_          [7]byte
}

type socketEventsSocketCursor struct {
	_         structs.HostLayout
	Pointer   uint64
	Left      uint64
	Remaining uint64
	Offset    uint64
	Segment   uint64
	Iov       uint64
	NrSegs    uint64
}

type socketEventsSocketRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	Skaddr      uint64
	PeerSkaddr  uint64
	CgroupId    uint64
	Result      int64
	EventType   uint32
	Pid         uint32
	PeerPid     uint32
	Len         uint32
	Offset      uint32
	Side        uint8
	Flags       uint8
	Pad         [2]uint8
	Comm        [16]int8
	Payload     [16384]uint8
}

type socketEventsSocketTarget struct {
	_   structs.HostLayout
	Ino uint64
	Dev uint32
	Pad uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	socketEventsMapEvents                  = "events"
	socketEventsMapLostEvents              = "lost_events"
	socketEventsMapSocketCalls             = "socket_calls"
	socketEventsMapSocketCursors           = "socket_cursors"
	socketEventsMapSocketScratch           = "socket_scratch"
	socketEventsMapSocketSides             = "socket_sides"
	socketEventsMapSocketTargets           = "socket_targets"
	socketEventsProgUnixReleaseEntry       = "unix_release_entry"
	socketEventsProgUnixStreamConnectExit  = "unix_stream_connect_exit"
	socketEventsProgUnixStreamRecvmsgEntry = "unix_stream_recvmsg_entry"
	socketEventsProgUnixStreamRecvmsgExit  = "unix_stream_recvmsg_exit"
	socketEventsProgUnixStreamSendmsgEntry = "unix_stream_sendmsg_entry"
	socketEventsProgUnixStreamSendmsgExit  = "unix_stream_sendmsg_exit"
	socketEventsVarPayloadLimit            = "payload_limit"
	socketEventsVarTargetPath              = "target_path"
	socketEventsVarUnusedSocketRecord      = "unused_socket_record"
)

// loadSocketEvents returns the embedded CollectionSpec for socketEvents.
func loadSocketEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SocketEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load socketEvents: %w", err)
	}

	return spec, err
}

// loadSocketEventsObjects loads socketEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*socketEventsObjects
//	*socketEventsPrograms
//	*socketEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSocketEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSocketEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// socketEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketEventsSpecs struct {
	socketEventsProgramSpecs
	socketEventsMapSpecs
	socketEventsVariableSpecs
}

// socketEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketEventsProgramSpecs struct {
	UnixReleaseEntry       *ebpf.ProgramSpec `ebpf:"unix_release_entry"`
	UnixStreamConnectExit  *ebpf.ProgramSpec `ebpf:"unix_stream_connect_exit"`
	UnixStreamRecvmsgEntry *ebpf.ProgramSpec `ebpf:"unix_stream_recvmsg_entry"`
	UnixStreamRecvmsgExit  *ebpf.ProgramSpec `ebpf:"unix_stream_recvmsg_exit"`
	UnixStreamSendmsgEntry *ebpf.ProgramSpec `ebpf:"unix_stream_sendmsg_entry"`
	UnixStreamSendmsgExit  *ebpf.ProgramSpec `ebpf:"unix_stream_sendmsg_exit"`
}

// socketEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketEventsMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	LostEvents    *ebpf.MapSpec `ebpf:"lost_events"`
	SocketCalls   *ebpf.MapSpec `ebpf:"socket_calls"`
	SocketCursors *ebpf.MapSpec `ebpf:"socket_cursors"`
	SocketScratch *ebpf.MapSpec `ebpf:"socket_scratch"`
	SocketSides   *ebpf.MapSpec `ebpf:"socket_sides"`
	SocketTargets *ebpf.MapSpec `ebpf:"socket_targets"`
}

// socketEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketEventsVariableSpecs struct {
	PayloadLimit       *ebpf.VariableSpec `ebpf:"payload_limit"`
	TargetPath         *ebpf.VariableSpec `ebpf:"target_path"`
	UnusedSocketRecord *ebpf.VariableSpec `ebpf:"unused_socket_record"`
}

// socketEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSocketEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketEventsObjects struct {
	socketEventsPrograms
	socketEventsMaps
	socketEventsVariables
}

func (o *socketEventsObjects) Close() error {
	return _SocketEventsClose(
		&o.socketEventsPrograms,
		&o.socketEventsMaps,
	)
}

// socketEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSocketEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketEventsMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	LostEvents    *ebpf.Map `ebpf:"lost_events"`
	SocketCalls   *ebpf.Map `ebpf:"socket_calls"`
	SocketCursors *ebpf.Map `ebpf:"socket_cursors"`
	SocketScratch *ebpf.Map `ebpf:"socket_scratch"`
	SocketSides   *ebpf.Map `ebpf:"socket_sides"`
	SocketTargets *ebpf.Map `ebpf:"socket_targets"`
}

func (m *socketEventsMaps) Close() error {
	return _SocketEventsClose(
		m.Events,
		m.LostEvents,
		m.SocketCalls,
		m.SocketCursors,
		m.SocketScratch,
		m.SocketSides,
		m.SocketTargets,
	)
}

// socketEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSocketEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketEventsVariables struct {
	PayloadLimit       *ebpf.Variable `ebpf:"payload_limit"`
	TargetPath         *ebpf.Variable `ebpf:"target_path"`
	UnusedSocketRecord *ebpf.Variable `ebpf:"unused_socket_record"`
}

// socketEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSocketEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketEventsPrograms struct {
	UnixReleaseEntry       *ebpf.Program `ebpf:"unix_release_entry"`
	UnixStreamConnectExit  *ebpf.Program `ebpf:"unix_stream_connect_exit"`
	UnixStreamRecvmsgEntry *ebpf.Program `ebpf:"unix_stream_recvmsg_entry"`
	UnixStreamRecvmsgExit  *ebpf.Program `ebpf:"unix_stream_recvmsg_exit"`
	UnixStreamSendmsgEntry *ebpf.Program `ebpf:"unix_stream_sendmsg_entry"`
	UnixStreamSendmsgExit  *ebpf.Program `ebpf:"unix_stream_sendmsg_exit"`
}

func (p *socketEventsPrograms) Close() error {
	return _SocketEventsClose(
		p.UnixReleaseEntry,
		p.UnixStreamConnectExit,
		p.UnixStreamRecvmsgEntry,
		p.UnixStreamRecvmsgExit,
		p.UnixStreamSendmsgEntry,
		p.UnixStreamSendmsgExit,
	)
}

func _SocketEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed socketevents_bpfeb.o
var _SocketEventsBytes []byte
