// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlsPlaintextArgs struct {
	_      structs.HostLayout
	Ssl    uint64
	Buf    uint64
	OutLen uint64
}

type tlsPlaintextTlsPlaintextRecord struct {
	_           structs.HostLayout
	TimestampNs uint64
	Ssl         uint64
	Tgid        uint32
	Tid         uint32
	Kind        uint32
	DataLen     uint32
	OriginalLen uint32
	Pad         uint32
	Comm        [16]int8
	Data        [16384]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlsPlaintextMapAllowedCgroups   = "allowed_cgroups"
	tlsPlaintextMapEvents           = "events"
	tlsPlaintextMapReads            = "reads"
	tlsPlaintextMapReadsEx          = "reads_ex"
	tlsPlaintextMapWrites           = "writes"
	tlsPlaintextMapWritesEx         = "writes_ex"
	tlsPlaintextProgTlsClose        = "tls_close"
	tlsPlaintextProgTlsReadEnter    = "tls_read_enter"
	tlsPlaintextProgTlsReadExEnter  = "tls_read_ex_enter"
	tlsPlaintextProgTlsReadExExit   = "tls_read_ex_exit"
	tlsPlaintextProgTlsReadExit     = "tls_read_exit"
	tlsPlaintextProgTlsWriteEnter   = "tls_write_enter"
	tlsPlaintextProgTlsWriteExEnter = "tls_write_ex_enter"
	tlsPlaintextProgTlsWriteExExit  = "tls_write_ex_exit"
	tlsPlaintextProgTlsWriteExit    = "tls_write_exit"
	tlsPlaintextVarAllowAll         = "allow_all"
	tlsPlaintextVarTargetPid        = "target_pid"
	tlsPlaintextVarUnusedRecord     = "unused_record"
)

// loadTlsPlaintext returns the embedded CollectionSpec for tlsPlaintext.
func loadTlsPlaintext() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsPlaintextBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlsPlaintext: %w", err)
	}

	return spec, err
}

// loadTlsPlaintextObjects loads tlsPlaintext and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlsPlaintextObjects
//	*tlsPlaintextPrograms
//	*tlsPlaintextMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlsPlaintextObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlsPlaintext()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlsPlaintextSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsPlaintextSpecs struct {
	tlsPlaintextProgramSpecs
	tlsPlaintextMapSpecs
	tlsPlaintextVariableSpecs
}

// tlsPlaintextProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsPlaintextProgramSpecs struct {
	TlsClose        *ebpf.ProgramSpec `ebpf:"tls_close"`
	TlsReadEnter    *ebpf.ProgramSpec `ebpf:"tls_read_enter"`
	TlsReadExEnter  *ebpf.ProgramSpec `ebpf:"tls_read_ex_enter"`
	TlsReadExExit   *ebpf.ProgramSpec `ebpf:"tls_read_ex_exit"`
	TlsReadExit     *ebpf.ProgramSpec `ebpf:"tls_read_exit"`
	TlsWriteEnter   *ebpf.ProgramSpec `ebpf:"tls_write_enter"`
	TlsWriteExEnter *ebpf.ProgramSpec `ebpf:"tls_write_ex_enter"`
	TlsWriteExExit  *ebpf.ProgramSpec `ebpf:"tls_write_ex_exit"`
	TlsWriteExit    *ebpf.ProgramSpec `ebpf:"tls_write_exit"`
}

// tlsPlaintextMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsPlaintextMapSpecs struct {
	AllowedCgroups *ebpf.MapSpec `ebpf:"allowed_cgroups"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	Reads          *ebpf.MapSpec `ebpf:"reads"`
	ReadsEx        *ebpf.MapSpec `ebpf:"reads_ex"`
	Writes         *ebpf.MapSpec `ebpf:"writes"`
	WritesEx       *ebpf.MapSpec `ebpf:"writes_ex"`
}

// tlsPlaintextVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlsPlaintextVariableSpecs struct {
	AllowAll     *ebpf.VariableSpec `ebpf:"allow_all"`
	TargetPid    *ebpf.VariableSpec `ebpf:"target_pid"`
	UnusedRecord *ebpf.VariableSpec `ebpf:"unused_record"`
}

// tlsPlaintextObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlsPlaintextObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPlaintextObjects struct {
	tlsPlaintextPrograms
	tlsPlaintextMaps
	tlsPlaintextVariables
}

func (o *tlsPlaintextObjects) Close() error {
	return _TlsPlaintextClose(
		&o.tlsPlaintextPrograms,
		&o.tlsPlaintextMaps,
	)
}

// tlsPlaintextMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlsPlaintextObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPlaintextMaps struct {
	AllowedCgroups *ebpf.Map `ebpf:"allowed_cgroups"`
	Events         *ebpf.Map `ebpf:"events"`
	Reads          *ebpf.Map `ebpf:"reads"`
	ReadsEx        *ebpf.Map `ebpf:"reads_ex"`
	Writes         *ebpf.Map `ebpf:"writes"`
	WritesEx       *ebpf.Map `ebpf:"writes_ex"`
}

func (m *tlsPlaintextMaps) Close() error {
	return _TlsPlaintextClose(
		m.AllowedCgroups,
		m.Events,
		m.Reads,
		m.ReadsEx,
		m.Writes,
		m.WritesEx,
	)
}

// tlsPlaintextVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlsPlaintextObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPlaintextVariables struct {
	AllowAll     *ebpf.Variable `ebpf:"allow_all"`
	TargetPid    *ebpf.Variable `ebpf:"target_pid"`
	UnusedRecord *ebpf.Variable `ebpf:"unused_record"`
}

// tlsPlaintextPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlsPlaintextObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlsPlaintextPrograms struct {
	TlsClose        *ebpf.Program `ebpf:"tls_close"`
	TlsReadEnter    *ebpf.Program `ebpf:"tls_read_enter"`
	TlsReadExEnter  *ebpf.Program `ebpf:"tls_read_ex_enter"`
	TlsReadExExit   *ebpf.Program `ebpf:"tls_read_ex_exit"`
	TlsReadExit     *ebpf.Program `ebpf:"tls_read_exit"`
	TlsWriteEnter   *ebpf.Program `ebpf:"tls_write_enter"`
	TlsWriteExEnter *ebpf.Program `ebpf:"tls_write_ex_enter"`
	TlsWriteExExit  *ebpf.Program `ebpf:"tls_write_ex_exit"`
	TlsWriteExit    *ebpf.Program `ebpf:"tls_write_exit"`
}

func (p *tlsPlaintextPrograms) Close() error {
	return _TlsPlaintextClose(
		p.TlsClose,
		p.TlsReadEnter,
		p.TlsReadExEnter,
		p.TlsReadExExit,
		p.TlsReadExit,
		p.TlsWriteEnter,
		p.TlsWriteExEnter,
		p.TlsWriteExExit,
		p.TlsWriteExit,
	)
}

func _TlsPlaintextClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlsplaintext_bpfel.o
var _TlsPlaintextBytes []byte
