// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package edc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type topProcessEventsIoStart struct {
	_       structs.HostLayout
	StartNs uint64
	Bytes   uint64
	Tgid    uint32
	Pad     uint32
}

type topProcessEventsProcessStats struct {
	_         structs.HostLayout
	RunqCount uint64
	RunqSumNs uint64
	RunqHist  [24]uint64
	IoCount   uint64
	IoBytes   uint64
	IoSumNs   uint64
	IoHist    [24]uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	topProcessEventsMapIoPending          = "io_pending"
	topProcessEventsMapRunqStart          = "runq_start"
	topProcessEventsMapStats              = "stats"
	topProcessEventsMapWatched            = "watched"
	topProcessEventsProgTopComplete       = "top_complete"
	topProcessEventsProgTopExit           = "top_exit"
	topProcessEventsProgTopIssue          = "top_issue"
	topProcessEventsProgTopRequeue        = "top_requeue"
	topProcessEventsProgTopSwitch         = "top_switch"
	topProcessEventsProgTopWakeup         = "top_wakeup"
	topProcessEventsProgTopWakeupNew      = "top_wakeup_new"
	topProcessEventsVarTargetNsInum       = "target_ns_inum"
	topProcessEventsVarUnusedProcessStats = "unused_process_stats"
)

// loadTopProcessEvents returns the embedded CollectionSpec for topProcessEvents.
func loadTopProcessEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TopProcessEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load topProcessEvents: %w", err)
	}

	return spec, err
}

// loadTopProcessEventsObjects loads topProcessEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*topProcessEventsObjects
//	*topProcessEventsPrograms
//	*topProcessEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTopProcessEventsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTopProcessEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// topProcessEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type topProcessEventsSpecs struct {
	topProcessEventsProgramSpecs
	topProcessEventsMapSpecs
	topProcessEventsVariableSpecs
}

// topProcessEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type topProcessEventsProgramSpecs struct {
	TopComplete  *ebpf.ProgramSpec `ebpf:"top_complete"`
	TopExit      *ebpf.ProgramSpec `ebpf:"top_exit"`
	TopIssue     *ebpf.ProgramSpec `ebpf:"top_issue"`
	TopRequeue   *ebpf.ProgramSpec `ebpf:"top_requeue"`
	TopSwitch    *ebpf.ProgramSpec `ebpf:"top_switch"`
	TopWakeup    *ebpf.ProgramSpec `ebpf:"top_wakeup"`
	TopWakeupNew *ebpf.ProgramSpec `ebpf:"top_wakeup_new"`
}

// topProcessEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type topProcessEventsMapSpecs struct {
	IoPending *ebpf.MapSpec `ebpf:"io_pending"`
	RunqStart *ebpf.MapSpec `ebpf:"runq_start"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
	Watched   *ebpf.MapSpec `ebpf:"watched"`
}

// topProcessEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type topProcessEventsVariableSpecs struct {
	TargetNsInum       *ebpf.VariableSpec `ebpf:"target_ns_inum"`
	UnusedProcessStats *ebpf.VariableSpec `ebpf:"unused_process_stats"`
}

// topProcessEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTopProcessEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type topProcessEventsObjects struct {
	topProcessEventsPrograms
	topProcessEventsMaps
	topProcessEventsVariables
}

func (o *topProcessEventsObjects) Close() error {
	return _TopProcessEventsClose(
		&o.topProcessEventsPrograms,
		&o.topProcessEventsMaps,
	)
}

// topProcessEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTopProcessEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type topProcessEventsMaps struct {
	IoPending *ebpf.Map `ebpf:"io_pending"`
	RunqStart *ebpf.Map `ebpf:"runq_start"`
	Stats     *ebpf.Map `ebpf:"stats"`
	Watched   *ebpf.Map `ebpf:"watched"`
}

func (m *topProcessEventsMaps) Close() error {
	return _TopProcessEventsClose(
		m.IoPending,
		m.RunqStart,
		m.Stats,
		m.Watched,
	)
}

// topProcessEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTopProcessEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type topProcessEventsVariables struct {
	TargetNsInum       *ebpf.Variable `ebpf:"target_ns_inum"`
	UnusedProcessStats *ebpf.Variable `ebpf:"unused_process_stats"`
}

// topProcessEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTopProcessEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type topProcessEventsPrograms struct {
	TopComplete  *ebpf.Program `ebpf:"top_complete"`
	TopExit      *ebpf.Program `ebpf:"top_exit"`
	TopIssue     *ebpf.Program `ebpf:"top_issue"`
	TopRequeue   *ebpf.Program `ebpf:"top_requeue"`
	TopSwitch    *ebpf.Program `ebpf:"top_switch"`
	TopWakeup    *ebpf.Program `ebpf:"top_wakeup"`
	TopWakeupNew *ebpf.Program `ebpf:"top_wakeup_new"`
}

func (p *topProcessEventsPrograms) Close() error {
	return _TopProcessEventsClose(
		p.TopComplete,
		p.TopExit,
		p.TopIssue,
		p.TopRequeue,
		p.TopSwitch,
		p.TopWakeup,
		p.TopWakeupNew,
	)
}

func _TopProcessEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed topprocessevents_bpfeb.o
var _TopProcessEventsBytes []byte
